version: '3'
services:
  my-app:
    image: my-node-app:1.0
    ports:
     - 3000:3000
    nvironment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
    networks:
      - shared_net

networks:
  shared_net:
    name: shared_net
