version: '3'
services:
  node_app:
    image: node_app:1.0
    container_name: node_app
    ports:
     - 3000:3000
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
    networks:
      - shared_net

networks:
  shared_net:
    name: shared_net
